### PR TITLE
added template files and view logic for breadcrumbs, which can be use…

### PR DESCRIPTION
**Pull request by aszepieniec**
…ful for wikis with a hierarchical structure

feature can be activated  by setting WALIKI_BREADCRUMBS to True in waliki/settings.py

### CODE REVIEW

**Comment by mgaitan** [comment]
wonderful contribution, thank you! 

My first daughter was born few weeks ago and that, obviously, take me away of github and my open source project, but let me few days to get back and I'll merge it. 

PS: if you can catch what's breaking travis in all the PR, I would be very pleased to know it.

**Comment by aszepieniec** [comment]
Glad you appreciate it. Unfortunately, I have no idea what's breaking travis or even how to start figuring out. Have fun with your daughter ;)

**Comment by RobertoMaurizzi** [comment]
I looks like you're including a wrong version of Hovercraft: it says "Hovercraft requires Python 3.2 or higher."
Since the pull request doesn't change requirements.txt it's innocent, it's likely that something changed in Hovercraft's pypi version.
I seem to remember having similar problems with Hovercraft when I installed my test setup a while ago, unfortunately I didn't have any time to better study Waliki for the past few weeks  :-/

**Comment by RobertoMaurizzi** [comment]
More on the topic of @aszepieniec's pull request, shouldn't waliki/settings.py change be like this?

    -WALIKI_BREADCRUMBS = False
    +WALIKI_BREADCRUMBS = getattr(settings, 'WALIKI_BREADCRUMBS', False)

If I don't do this, WALIKI_BREADCRUMBS = True in my settings.py gets overridden to False.

**Comment by aszepieniec** [comment]
RobertoMaurizzi: Yeah, that makes a lot more sense. There's no reason this configuration variable should be defined differently from all the other ones.

Forgive me, I'm still learning.

**Comment by mgaitan** [comment]
Thanks @aszepieniec , I've just merged

**Pull request merged**
